L1: 0.32
L2: 0.27
L3: 0.1
m2: 1.5
m3: 0.0
b1: 0.5
k1: 2.3
theta1: 100.0
I233: 0.013
g: -9.81

pos_ctrl:
  kp: 0.4
  ki: 0.5
  kd: 3.0

force_ctrl:
  kp: 30.0

calibration:
  interval: 10
  duration: 2
  wait: 1