L1: 0.32
L2: 0.27
L3: 0.1
m2: 1.5
m3: 0.0
b1: 0.5
k1: 2.3
theta1: 100.0
I233: 0.013
g: -9.81
min: 10.0
max: 100.0

pos_ctrl:
  kp: 0.4
  ki: 0.5
  kd: 3.0

force_ctrl:
  kp_up: 7.5
  kp_down: 6.5
  ki_up: 2.0
  ki_down: 2.0
  kd_up: 0.0
  kd_down: 0.0

calibration:
  interval: 10.0
  duration: 3.0
  wait: 2.0